name = "cf-workers-bingai-sydney-discord-bot"
main = "src/index.ts"
compatibility_date = "2023-03-02"
workers_dev = true

kv_namespaces = [
    { binding = "BINGAI_SYDNEY_DISCORD_BOT_KV", id = "e9c1cd16078e44449741f5e47e95bb3e" }
]

[vars]
DISCORD_USERID_WHITELIST = "115383559790919689 149263431638188032 360096828609396737 150581926489620481" # jaryl jazz jonsee sakthi,
BING_CONVERSATION_STYLE = "BALANCED" # balanced (recommended)
#BING_CONVERSATION_STYLE = "CREATIVE" # creative
#BING_CONVERSATION_STYLE = "PRECISE" # precise
#BING_BEHAVIOR = "You're a an AI assistant named Sydney." # BROKEN
